server.port=8081


# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/proiect_colecitv
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
googlebooks.apiKey=AIzaSyDqh1wwYR7i-g8DRf5FgtGvA01KN56qdj8

# Spotify OAuth
spotify.client.id='30f929bea61b4dceaa7496b17b8542c0'
spotify.client.secret=YOUR_SPOTIFY_CLIENT_SECRET
spotify.redirect.uri=http://127.0.0.1:3001/callback

# JWT
app.jwt.secret=ceva_lung_random_schimba_asta_12345678901234567890
app.jwt.expiration-ms=86400000